import { ITEM_CONCURRENCY } from "../config.mts";
import { PLATFORM_CONFIG } from "./platform-config.mts";
import type { GeneratedImage, ImageProvider } from "./provider.mts";
import { generateWithFailover, type ResilienceOptions } from "./resilience.mts";
import type { Platform } from "./schema.mts";
import type { Batch, BatchItem, Post } from "./types.mts";

// Generated bytes are served inline as a data URL — no storage infrastructure
// needed, and the browser demo renders them directly. (Upgrade path: write to
// outputs/ + S3, see ADR 0001.)
function toDataUrl(image: GeneratedImage): string {
	return `data:${image.mimeType};base64,${Buffer.from(image.imageBytes).toString("base64")}`;
}

// Assemble the post returned to the client from what the provider generated plus
// platform metadata; records which provider produced it.
function buildPost(image: GeneratedImage, platform: Platform, provider: string): Post {
	return {
		imageUrl: toDataUrl(image),
		caption: image.caption,
		hashtags: image.hashtags,
		platform,
		meta: { provider, aspectRatio: PLATFORM_CONFIG[platform].aspectRatio },
	};
}

async function processItem(
	item: BatchItem,
	batch: Batch,
	providers: ImageProvider[],
	options: ResilienceOptions,
): Promise<void> {
	item.status = "running";
	try {
		const { image, provider } = await generateWithFailover(
			providers,
			item.product,
			batch.references,
			batch.styleSpec,
			PLATFORM_CONFIG[batch.platform],
			options,
		);
		item.post = buildPost(image, batch.platform, provider);
		item.status = "done";
	} catch (error) {
		// Both providers exhausted their retries — record the last error and move
		// on so one failed item never sinks the batch.
		item.status = "failed";
		item.error = error instanceof Error ? error.message : String(error);
	}
}

// Drives a batch to completion: pending -> running, each item generated through
// the provider seam with retry/failover and bounded concurrency, then the batch
// settles to done. Resolves when every item is terminal; callers that want async
// behaviour invoke this without awaiting.
export async function processBatch(
	batch: Batch,
	providers: ImageProvider[],
	options: ResilienceOptions = {},
): Promise<void> {
	batch.status = "running";

	const queue = batch.items.values();
	const workers: Promise<void>[] = [];
	const workerCount = Math.min(ITEM_CONCURRENCY, batch.items.length);
	for (let i = 0; i < workerCount; i++) {
		workers.push(
			(async () => {
				for (const item of queue) {
					await processItem(item, batch, providers, options);
				}
			})(),
		);
	}
	await Promise.all(workers);

	batch.status = "done";
}
