import { ITEM_CONCURRENCY } from "../config.mts";
import { type OutputWriter, writeOutput } from "./outputs.mts";
import { PLATFORM_CONFIG } from "./platform-config.mts";
import type { GeneratedImage, ImageProvider } from "./provider.mts";
import { generateWithFailover, type ResilienceOptions } from "./resilience.mts";
import type { Platform } from "./schema.mts";
import type { Batch, BatchItem, Post } from "./types.mts";

// Options threaded through a run: the resilience knobs (retry/failover, with
// injectable sleep/random for tests) plus the image sink. writeImage defaults to
// the on-disk outputs/ writer; tests inject a stub to avoid touching disk.
export type ProcessOptions = ResilienceOptions & { writeImage?: OutputWriter };

// Assemble the post returned to the client: persist the generated bytes to
// outputs/, then pair the served URL with caption/hashtags and platform
// metadata; records which provider produced it.
async function buildPost(
	image: GeneratedImage,
	platform: Platform,
	provider: string,
	name: string,
	writeImage: OutputWriter,
): Promise<Post> {
	const imageUrl = await writeImage(image, name);
	return {
		imageUrl,
		caption: image.caption,
		hashtags: image.hashtags,
		platform,
		meta: { provider, aspectRatio: PLATFORM_CONFIG[platform].aspectRatio },
	};
}

async function processItem(
	index: number,
	item: BatchItem,
	batch: Batch,
	providers: ImageProvider[],
	options: ResilienceOptions,
	writeImage: OutputWriter,
): Promise<void> {
	item.status = "running";
	try {
		const { image, provider } = await generateWithFailover(
			providers,
			item.product,
			batch.references,
			batch.styleSpec,
			PLATFORM_CONFIG[batch.platform],
			options,
		);
		item.post = await buildPost(image, batch.platform, provider, `${batch.id}-${index}`, writeImage);
		item.status = "done";
	} catch (error) {
		// Both providers exhausted their retries — record the last error and move
		// on so one failed item never sinks the batch.
		item.status = "failed";
		item.error = error instanceof Error ? error.message : String(error);
	}
}

// Drives a batch to completion: pending -> running, each item generated through
// the provider seam with retry/failover and bounded concurrency, then the batch
// settles to done. Resolves when every item is terminal; callers that want async
// behaviour invoke this without awaiting.
export async function processBatch(
	batch: Batch,
	providers: ImageProvider[],
	options: ProcessOptions = {},
): Promise<void> {
	batch.status = "running";

	const { writeImage = writeOutput, ...resilience } = options;
	// entries() yields [index, item]; the index keys the on-disk output filename.
	const queue = batch.items.entries();
	const workers: Promise<void>[] = [];
	const workerCount = Math.min(ITEM_CONCURRENCY, batch.items.length);
	for (let i = 0; i < workerCount; i++) {
		workers.push(
			(async () => {
				for (const [index, item] of queue) {
					await processItem(index, item, batch, providers, resilience, writeImage);
				}
			})(),
		);
	}
	await Promise.all(workers);

	batch.status = "done";
}
